### ISSUE TITLE
'DEV_SERVER' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by schmendrick** [itajaja/hb#6]
Steps to reproduce:

Try to run as readme states:

> yarn
>npm run start

results in error:
> DEV_SERVER=true webpack-dev-server --hot --inline --progress

'DEV_SERVER' is not recognized as an internal or external command

**Comment by itajaja** [comment]
Hi, looks like you are on windows... use a POSIX compatible shell at least, that should solve the problem.

https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

you might encounter other problems using windows, as I've never tried to run this on windows. Let me know if you have other problems ✌️
